run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck

issues:
  exclude-rules:
    - path: context\.go
      linters:
        - errcheck
    - path: engine\.go
      linters:
        - errcheck
    - path: cmd/vodka/main\.go
      source: os\.Mkdir\(
      linters:
        - errcheck
    - path: cmd/vodka/main\.go
      source: appCmd\.Wait\(
      linters:
        - errcheck
    - path: cmd/vodka/main\.go
      source: appCmd\.Process\.Kill\(
      linters:
        - errcheck
    - path: cmd/vodka/main\.go
      source: os\.WriteFile\(
      linters:
        - errcheck
    - path: cmd/vodka/main\.go
      source: os\.MkdirAll\(
      linters:
        - errcheck