name: Update Contributors

on:
  push:
    branches:
      - main
      - contributors
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours


jobs:
  contributors:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Update Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image_size: 80
          columns_per_row: 6
          use_username: true
          commit_message: "docs: update contributors"