name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version: "1.24.0"
          cache: true
          cache-dependency-path: go.sum
      
      - name: Verify Dependencies
        run: go mod tidy && git diff --exit-code

      - name: Run Tests
        run: go test $(go list ./... | grep -v /examples/) -v

      - name: Run race detector
        run: go test -race $(go list ./... | grep -v /examples/)

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version: "1.24.0"
          cache: true
          cache-dependency-path: go.sum

      - name: Run coverage tests
        run: go test ./... -coverprofile=coverage.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: coverage
          path: coverage.out